### ISSUE TITLE
対局開始でエラー

### ISSUE THREAD

**Issue by vochicong** [jnory/MyShogiInstaller#2]
おかげさまで #1 ビルドができました。
早速対局してみると、エラーが発生したのでレポートいたします。

## 対局エンジンの選択

<img width="598" alt="2018-12-20 13 49 18" src="https://user-images.githubusercontent.com/123111/50264481-45714980-045e-11e9-9c6a-301e1ad483a9.png">

## 対局開始ボタンを押下

<img width="763" alt="2018-12-20 13 49 27" src="https://user-images.githubusercontent.com/123111/50264492-5457fc00-045e-11e9-8e8c-964a187d867d.png">

## 例外が発生
<img width="999" alt="2018-12-20 13 49 45" src="https://user-images.githubusercontent.com/123111/50264503-60dc5480-045e-11e9-90aa-807d2fb0a69e.png">

**Comment by jnory** [comment]
#1 でお返事できておらず申し訳ありません。(そちらの方はできるだけ近いうちに確認します！)
起動できたようでよかったです。

右下の読み筋のところに見切れていますが、モデルファイルか定跡ファイルの置き場所と設定が不一致になっているのが原因です。(このエラーは私も開発中に発生して直したはずだったのですが…)

真ん中のスクリーンショットでエンジンの詳細設定に進み、evalディレクトリのパスを修正すれば直るはずです。(たしかエンジンのパスからの相対パスで指定するはずです)

もしそれでも直らない場合、メニューのどこかにデバッグ情報をファイルに書き出すオプションがありますのでその出力結果をお見せいただけますと助かります。(今手元に環境がなくうろ覚えで申し訳ありません…)

**Comment by vochicong** [comment]
できました！
コメントに従ってエンジンの確認をしたところ、bookフォルダは正しく `../../book` になっていますが、 eval フォルダが `eval` になっていたので、 `../../eval` に直しました。
その結果、対局ができるようになりました！
ありがとうございました。

![2018-12-20 18 52 59](https://user-images.githubusercontent.com/123111/50278868-90ee1c80-048b-11e9-80bd-73a4d943ff3a.png)

![2018-12-20 19 13 13](https://user-images.githubusercontent.com/123111/50278793-5edcba80-048b-11e9-946d-c0054409424c.png)

**Comment by jnory** [comment]
無事動いてよかったです！不具合の方、後日修正させていただきます！(修正次第こちらのissueを閉じさせていただきますね)

**Comment by jnory** [comment]
現在確認しております。

ここ https://github.com/jnory/MyShogiInstaller/blob/master/engine_defines/yaneuraou2018/engine_define.xml#L468 に書かれたデフォルト値が使われるはずなのですが、なぜかその値が読み込まれず、 `eval` という値で上書きされているようです。

もしかしたらMyShogi本体の方の問題かもしれません。

**Comment by jnory** [comment]
https://github.com/jnory/MyShogiInstaller/commit/32f2e1cf8426032924ec3199fb965e54fdc877b4 
多分こちらの修正で直ったはずです。

Twitterでアドバイスいただいて engine_options.txtというファイルを追加することで解決しました。(もとtweetが消えてしまっており紹介できなくて残念)
